var verbs, nouns, adjectives, adverbs, preposition;
            nouns = ["with", "without", "and", "or"];
            verbs = ["like",
            "love",
            "enjoy",
            "dislike",
            "hate",
            "prefer",
            "can’t stand"];

            adjectives = ["adorable",
            "agreeable",
            "amused",
            "annoying",
            "ashamed",
            "awful",
            "better",
            "bloody",
            "blushing",
            "brave",
            "busy",
            "cautious",
            "clean",
            "cloudy",
            "combative",
            "condemned",
            "courageous",
            "crowded",
            "cute",
            "dead",
            "delightful",
            "different",
            "distinct",
            "doubtful",
            "adventurous",
            "alert",
            "angry",
            "anxious",
            "attractive",
            "bad",
            "bewildered",
            "blue",
            "bored",
            "breakable",
            "calm",
            "charming",
            "clear",
            "clumsy",
            "comfortable",
            "confused",
            "crazy",
            "cruel",
            "dangerous",
            "defeated",
            "depressed",
            "difficult",
            "disturbed",
            "drab",
            "aggressive",
            "alive",
            "annoyed",
            "arrogant",
            "average",
            "beautiful",
            "black",
            "blue-eyed",
            "brainy",
            "bright",
            "careful",
            "cheerful",
            "clever",
            "colorful",
            "concerned",
            "cooperative",
            "creepy",
            "curious",
            "dark",
            "defiant",
            "determined",
            "disgusted",
            "dizzy",
            "dull",
            "eager",
            "elegant",
            "encouraging",
            "envious",
            "expensive",
            "faithful",
            "fantastic",
            "fine",
            "frail",
            "frightened",
            "gifted",
            "glorious",
            "graceful",
            "grumpy",
            "healthy",
            "hilarious",
            "horrible",
            "ill",
            "inexpensive",
            "itchy",
            "jolly",
            "easy",
            "embarrassed",
            "energetic",
            "evil",
            "exuberant",
            "famous",
            "fierce",
            "foolish",
            "frantic",
            "funny",
            "glamorous",
            "good",
            "grieving",
            "handsome",
            "helpful",
            "homeless",
            "hungry",
            "important",
            "innocent",
            "jealous",
            "joyous",
            "elated",
            "enchanting",
            "enthusiastic",
            "excited",
            "fair",
            "fancy",
            "filthy",
            "fragile",
            "friendly",
            "gentle",
            "gleaming",
            "gorgeous",
            "grotesque",
            "happy",
            "helpless",
            "homely",
            "hurt",
            "impossible",
            "inquisitive",
            "jittery",
            "kind",
            "lazy",
            "lonely",
            "lucky",
            "modern",
            "mushy",
            "naughty",
            "nutty",
            "odd",
            "outrageous",
            "perfect",
            "poised",
            "precious",
            "putrid",
            "real",
            "rich",
            "shiny",
            "sleepy",
            "sore",
            "spotless",
            "stupid",
            "light",
            "long",
            "magnificent",
            "motionless",
            "mysterious",
            "nervous",
            "obedient",
            "old-fashioned",
            "outstanding",
            "plain",
            "poor",
            "prickly",
            "puzzled",
            "relieved",
            "scary",
            "shy",
            "smiling",
            "sparkling",
            "stormy",
            "successful",
            "lively",
            "lovely",
            "misty",
            "muddy",
            "nasty",
            "nice",
            "obnoxious",
            "open",
            "panicky",
            "pleasant",
            "powerful",
            "proud",
            "quaint",
            "repulsive",
            "selfish",
            "silly",
            "smoggy",
            "splendid",
            "strange",
            "super",
            "talented",
            "tender",
            "thankful",
            "tired",
            "ugliest",
            "unsightly",
            "uptight",
            "vivacious",
            "wicked",
            "witty",
            "wrong",
            "tame",
            "tense",
            "thoughtful",
            "tough",
            "ugly",
            "unusual",
            "vast",
            "wandering",
            "wide-eyed",
            "worried",
            "zany",
            "tasty",
            "terrible",
            "thoughtless",
            "troubled",
            "uninterested",
            "upset",
            "victorious",
            "weary",
            "wild",
            "worrisome",
            "zealous"];

            
            adverbs = [
              "Address Books",
"Air Mattress",
"Aluminum Foils",
"Bags",
"Batteries",
"Beddings",
"Blankets",
"Blenders",
"Books",
"Buckets",
"Carpets",
"Cell Phones",
"Clothes",
"Containers",
"Doorbells",
"Dust Pans",
"Envelopes",
"Extension Cords",
"Flashlights",
"Foams",
"Garments",
"Glasses",
"Globes",
"Gyms",
"Hammers",
"Heaters",
"Hot Plates",
"Ink Pens",
"Irons",
"Jams",
"Jewelry",
"Juicers",
"Kettles",
"Kitchens",
"Kittens",
"Lams",
"Lemons",
"Light Switches",
"Mails",
"Medicines",
"Mixers",
"Mousetraps",
"Napkins",
"Note Papers",
"Oil",
"Perfumes",
"Plums",
"Pressure Cookers",
"Printers",
"Radios",
"Record Players",
"Screw Drivers",
"Spare Keys",
"Stamps",
"Telephones",
"Tissues",
"Toilet Brushes",
"Torches",
"Umbrellas",
"Uniforms",
"Vacuums",
"Vents",
"Washers",
"Water Heaters",
"Yogurts",
"Air Conditioners",
"Alarm Clocks",
"Armchairs",
"Baskets",
"Beds",
"Binders",
"Blankets",
"Blow Dryers",
"Boxers",
"Cameras",
"Ceiling Fans",
"Chairs",
"Computers",
"Dishes",
"Dryers",
"Electric Fans",
"Espresso Makers",
"Fireplaces",
"Garbage",
"Gates",
"Glasses",
"Hair Dryers",
"Headphones",
"Ice Cream Makers",
"Insects",
"Jackets",
"Jars",
"Juices",
"Keys",
"Kites",
"Knives",
"Leaf Blowers",
"Lights",
"Locks",
"Makeup",
"Microwaves",
"Mugs",
"Necklaces",
"Novels",
"Ovens",
"Plates",
"Popcorn Makers",
"Pressure Fryers",
"Raincoats",
"Refrigerators",
"Socks",
"Spoons",
"Staplers",
"Toasters",
"Toothpaste",
"Towels",
"Underwears",
"Utensils",
"Vases",
"Wardrobe",
"Watches",
"X-rays",

          ];
            preposition = ["down", "into", "up", "on", "upon", "below", "above", "through", "across", "towards"];

            function randGen() {
              return Math.floor(Math.random() * 5);
            }

            function sentence() {
              var rand1 = Math.floor(Math.random() * verbs.length);
              var rand2 = Math.floor(Math.random() * adverbs.length);
              var rand3 = Math.floor(Math.random() * nouns.length);
              var rand4 = Math.floor(Math.random() * adjectives.length);
              var rand5 = rand2

              while(rand5 == rand2) {
                rand5 = Math.floor(Math.random() * adverbs.length);
              }

              var content = " I " + " " + verbs[rand1] + " " + adverbs[rand2] + " " + nouns[rand3] + " " + adjectives[rand4] + " " + adverbs[rand5] ;

              document.getElementById("sentence").innerHTML = content;
            };
            sentence()
            requestAnimationFrame(loop)
            function loop(){

              requestAnimationFrame(loop)
              if (pressed) {
                sentence()
              }
            }

            /*
            let pressed = false
            document.addEventListener('mousedown', function(){
              pressed = true
            })
            document.addEventListener('mouseup', function(){
              pressed = false
            })
            */

            document.addEventListener('keydown', function(){
              pressed = true
            })
            document.addEventListener('keyup', function(){
              pressed = false
            })

            document.addEventListener('touchstart', function(){
              pressed = true
            })
            document.addEventListener('touchend', function(){
              pressed = false
            })
